// <auto-generated />
using System;
using CustomerManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustomerManagement.Data.Migrations
{
    [DbContext(typeof(CustomerManagementContext))]
    partial class CustomerManagementContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CustomerManagement.Data.Models.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("County")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PostalTown")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PostCode");

                    b.HasIndex("PostalTown");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("38ed5f3f-3460-40ba-8009-93371fefdfa2"),
                            AddressLine1 = "22 Oil Drum Lane",
                            PostCode = "W1A 1AA",
                            PostalTown = "East Cheam"
                        },
                        new
                        {
                            Id = new Guid("7242a930-fc47-4244-a97d-52b515aea1e4"),
                            AddressLine1 = "22 Acacia Avenue",
                            PostCode = "M60 1AA",
                            PostalTown = "Salford"
                        });
                });

            modelBuilder.Entity("CustomerManagement.Data.Models.ContactDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ContactType")
                        .HasColumnType("int");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsPreferred")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Detail")
                        .IsUnique();

                    b.ToTable("ContactDetails");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f5eea8e5-accf-4593-bcd9-016a897cd0e1"),
                            ContactType = 0,
                            CustomerId = new Guid("e5eafda2-c5d9-46b5-b364-95bb6da27b58"),
                            Detail = "dcarter.customermanagement@gmail.com",
                            IsPreferred = true
                        },
                        new
                        {
                            Id = new Guid("de920a0d-9453-487b-9c65-4ee865bd417f"),
                            ContactType = 2,
                            CustomerId = new Guid("e5eafda2-c5d9-46b5-b364-95bb6da27b58"),
                            Detail = "0123456789",
                            IsPreferred = false
                        });
                });

            modelBuilder.Entity("CustomerManagement.Data.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Middlenames")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FirstName", "Surname");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e5eafda2-c5d9-46b5-b364-95bb6da27b58"),
                            FirstName = "Darcy",
                            Surname = "Carter",
                            Title = "Mr"
                        });
                });

            modelBuilder.Entity("CustomerManagement.Data.Models.CustomerAddress", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDefaultAddress")
                        .HasColumnType("bit");

                    b.HasKey("CustomerId", "AddressId");

                    b.HasIndex("AddressId");

                    b.ToTable("CustomerAddresses");

                    b.HasData(
                        new
                        {
                            CustomerId = new Guid("e5eafda2-c5d9-46b5-b364-95bb6da27b58"),
                            AddressId = new Guid("38ed5f3f-3460-40ba-8009-93371fefdfa2"),
                            IsDefaultAddress = true
                        },
                        new
                        {
                            CustomerId = new Guid("e5eafda2-c5d9-46b5-b364-95bb6da27b58"),
                            AddressId = new Guid("7242a930-fc47-4244-a97d-52b515aea1e4"),
                            IsDefaultAddress = false
                        });
                });

            modelBuilder.Entity("CustomerManagement.Data.Models.ContactDetail", b =>
                {
                    b.HasOne("CustomerManagement.Data.Models.Customer", "Customer")
                        .WithMany("ContactDetails")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CustomerManagement.Data.Models.CustomerAddress", b =>
                {
                    b.HasOne("CustomerManagement.Data.Models.Address", null)
                        .WithMany("CustomerAddresses")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CustomerManagement.Data.Models.Customer", null)
                        .WithMany("CustomerAddresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CustomerManagement.Data.Models.Address", b =>
                {
                    b.Navigation("CustomerAddresses");
                });

            modelBuilder.Entity("CustomerManagement.Data.Models.Customer", b =>
                {
                    b.Navigation("ContactDetails");

                    b.Navigation("CustomerAddresses");
                });
#pragma warning restore 612, 618
        }
    }
}
